# Generated by Django 3.0.8 on 2020-07-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=30)),
                ('state', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
